### ISSUE TITLE
No console output under Windows

### ISSUE THREAD

**Issue by DoctorVanGogh** [Martchus/tageditor#18]
Readme says to use 

> **CLI**
> *Usage*
> ```
> tageditor <operation> [options]
> ```
> Checkout the available operations and options with `--help`.

Well, at least on windows `--help` does nothing 
```
C:\Temp>tageditor --help

C:\Temp>
```
So using the CLI is a bit of a guessing game.

**Comment by Martchus** [comment]
Seems to be a Windows-specific issue. Here the output of `--help` under Linux (as a temporary workaround):

```
[martchus@thinkpad-martchus ~]$ tageditor --help
Tag Editor, version 2.2.0

Available arguments:
--qt-widgets-gui
  shows a Qt widgets based graphical user interface
  --lang, -l [language]
    sets the language for the Qt GUI
  --qmljsdebugger [port:<port_from>[,port_to][,host:<ip address>][,block]]
    enables QML debugging (see http://doc.qt.io/qt-5/qtquick-debugging.html)
  --style [style name]
    sets the Qt widgets style
  --icon-theme [theme name] [search path 1] [search path 2] ...
    sets the icon theme and additional theme search paths for the Qt GUI
  --font [name] [size]
    sets the font family and size (point) for the Qt GUI
  --library-paths [path 1] [path 2] ...
    sets the list of directories to search when loading libraries (all existing paths will be deleted)
  --platformtheme [qt5ct/kde/...]
    specifies the Qt platform theme to be used
  --file, -f [path]
    specifies the path of the file to be opened
  --renaming-utility
    launches the renaming utility instead of the main GUI

--print-field-names
  prints available field names

--info, -i
  displays general file information
  --files, -f [path 1] [path 2] ...
    specifies the path of the file(s) to be opened
  --verbose, -v
    be verbose

--get, -g
  displays the values of all specified tag fields (displays all fields if none specified)
  --fields, -n [title] [album] [artist] [trackpos] ...
    specifies the field names to be displayed
  --files, -f [path 1] [path 2] ...
    specifies the path of the file(s) to be opened
  --verbose, -v
    be verbose

--set, -s
  sets the specified tag information and attachments
  --values, -n [title=foo] [album=bar] [cover=/path/to/file] ...
    specifies the values to be set
  --files, -f [path 1] [path 2] ...
    specifies the path of the file(s) to be opened
  --doc-title, -d [title of first segment] [title of second segment] ...
    specifies the document title (has no affect if not supported by the container)
  --remove-other-fields
    removes ALL fields where no value has been provided for (to remove a specific field use eg. "album=")
  --treat-unknown-as-mp3
    if present unknown files will be treatet as MP3 files
  --id3v1-usage [always/keepexisting/never]
    specifies the ID3v1 usage (only used when already present by default); only relevant when dealing with MP3 files (or files treated as such)
  --id3v2-usage [always/keepexisting/never]
    specifies the ID3v2 usage (always used by default); only relevant when dealing with MP3 files (or files treated as such)
  --id3-init-on-create
    indicates whether to initialize newly created ID3 tags (according to specified usage) with the values of the already present ID3 tags
  --id3-transfer-on-removal
    indicates whether values of removed ID3 tags (according to specified usage) should be transfered to remaining ID3 tags (no values will be overwritten)
  --merge-successive-tags
    if present multiple successive ID3v2 tags will be merged
  --id3v2-version [1/2/3/4]
    forces a specific ID3v2 version to be used; only relevant when ID3v2 is used
  --encoding [latin1/utf8/utf16le/utf16be]
    specifies the preferred encoding
  --remove-target ...
    removes all tags with the specified target
  --add-attachment [path=some/file] [name=Some name] [desc=Some desc] [mime=mime/type] ...
    adds a new attachment
  --update-attachment [path=some/file] [name=Some name] [desc=Some desc] [mime=mime/type] ...
    updates an existing attachment
  --remove-attachment [name=to_remove]
    removes an existing attachment
  --remove-existing-attachments, -r
    removes ALL existing attachments (to remove a specific attachment use --remove-attachment)
  --min-padding [min padding in byte]
    specifies the minimum padding before the media data
  --max-padding [min padding in byte]
    specifies the maximum padding before the media data
  --preferred-padding [preferred padding in byte]
    specifies the preferred padding before the media data
  --tag-pos
    specifies the preferred tag position
    --value [front/back/current]
      specifies the position, either front, back or current
      particularities: mandatory if parent argument is present
    --force
      forces the specified position even if the file to be rewritten
  --index-pos
    specifies the preferred index position
    --value [front/back/current]
      specifies the position, either front, back or current
      particularities: mandatory if parent argument is present
    --force
      forces the specified position even if the file to be rewritten
  --force-rewrite
    forces the file to rewritten from the scratch
  --verbose, -v
    be verbose
  --output-files, -o [path 1] [path 2] ...
    specifies the output files; if present, the files specified with --files will not be modified

--extract, -e
  saves the value of the specified field (eg. cover or other binary field) or attachment to the specified file or writes it to stdout if no output file has been specified
  --field, -n [field name]
    specifies the field to be extracted
  --attachment, -a [id=...]
    specifies the attachment to be extracted
  --file, -f [path]
    specifies the path of the file to be opened
    particularities: mandatory if parent argument is present
  --output-file, -o [path]
    specifies the path of the output file
  --verbose, -v
    be verbose

--html-info
  generates technical information about the specified file as HTML document
  --file, -f [path]
    specifies the path of the file to be opened
    particularities: mandatory if parent argument is present
  --validate, -c
    validates the file integrity as accurately as possible; the structure of the file will be parsed completely
  --output-file, -o [path]
    specifies the path of the output file

--help, -h
  shows this information
```

I assume you use the latest Windows build from the release section here on GitHub? Do you use the default terminal (`cmd.exe`)? I suspect the problem is that it can not handle the formatting correctly.

Also because of other encoding related issues I would recommend to use MSYS2 terminal (or any other decent terminal) instead.

**Comment by DoctorVanGogh** [comment]
Used version is `2.1.1` (I think that was the lastest static windows build from your homepage - btw would a cli only build be significantly smaller than 20 MB?).

And yeah, there's definitely something wonky going on with the terminal. Cursor isn't at prompt after tageditor runs a command (example: `tageditor -s cover=foo.jpg -f foo.mp4` and scrollbar(s) are .... unexpected:

![before](https://cloud.githubusercontent.com/assets/324067/23973862/6ed9b99c-09d8-11e7-82c6-51abf9f4e357.png)

![after](https://cloud.githubusercontent.com/assets/324067/23973865/7324fb38-09d8-11e7-9dbc-09b1a1b600f4.png)

(ignore the IO error - I did use single quotes instead of double ones).

**Comment by Martchus** [comment]
Ok, so you're using the latest Windows development snapshot. I've just noticed that I forgot to upload some Windows binaries for the last releases on GitHub.

> would a cli only build be significantly smaller than 20 MB?

Yes. I could provide it as alternative. However, Windows builds and saving a few MB are not my biggest concern.

I'm not sure whether this build has the setting to enforce UTF-8 for Unicode support. This setting might do more harm than good because the UTF-8 support in `cmd.exe` is a complete mess. 
Which Windows version do you use?

**Comment by DoctorVanGogh** [comment]
Using Win 10 x64 1607.

Can confirm that a Mingw64 console one the same system has no issues with output.

**Comment by Martchus** [comment]
Ok, I'll have a look at the missing `--help` output. Maybe it is just broken in that particular build (not sure for which reason I created it). But I guess I can not do a lot about the other terminal issues. `cmd.exe` is just a mess and I don't want to put much effort in it.

**Comment by svnpenn** [comment]
@Martchus I can repro this. From this page:

http://martchus.no-ip.biz/repo/win/static

The last working build is

~~~
tageditor-release-2.1.0-static-x86_64-w64-mingw32
~~~

any build after that release or devel fails as shown above and now below:

> A tageditor with Qt GUI and command line interface. Supports MP4 (iTunes),
> ID3, Vorbis, Opus, FLAC and Matroska has stopped working

Confirmed with Windows 7 in pristine virtual machine. Please sort this. FFmpeg
works fine with cmd.exe, no reason TagEditor can’t do the same.

**Comment by svnpenn** [comment]
@Martchus I can repro this. From this page:

http://martchus.no-ip.biz/repo/win/static

The last working build is:

~~~
tageditor-release-2.1.0-static-x86_64-w64-mingw32
~~~

any build after that release or devel fails as shown above and now below:

> A tageditor with Qt GUI and command line interface. Supports MP4 (iTunes),
> ID3, Vorbis, Opus, FLAC and Matroska has stopped working

Confirmed with Windows 7 in pristine virtual machine. Please sort this. FFmpeg
works fine with cmd.exe, no reason TagEditor can’t do the same. If you are
unwilling to fix this and #15, you might want to seriously consider removing the
Windows build altogether. I don’t want to see this happen, but I would almost
rather have no Windows build at all than a crippled one.

**Comment by Martchus** [comment]
@svnpenn I do not put much effort into the Windows version. Note that the bugs only concern the CLI and only `cmd.exe` so I wouldn't cancel the windows version completely. I thought you would help to fix #15. My problem with the issue is that I just don't know how to fix it. Additionally, when I can just use a decent terminal, why care about `cmd.exe` so much?

**Comment by Martchus** [comment]
Ok, maybe the function `::ApplicationUtilities::startConsole()` defined in `applications/commandlineutils.cpp` of c++utilities doesn't work correctly. The method enables use of cerr/cout/cin in a GUI (or at least not solely CLI) application under Windows. It can be seen as a workaround. Under GNU/Linux this works out of the box.

Not sure why it suddenly stops working because I didn't touch it. Maybe new compiler/cmake/library version or different build configuration triggers the issue. However, a simple hello world example using my `startConsole()` function and built with `-mwindows` works here, too.

Interestingly it also fails in MSYS2 terminal. However, in this case the mentioned method isn't required. So maybe the error is somewhere else, though?

@svnpenn Does it work when building in your cygwin environment? Any ideas? I'm currently quite clueless. Windows specifics are not my area of expertise.

**Comment by svnpenn** [comment]
@Martchus master does not even build:

~~~
[ 14%] Building CXX object CMakeFiles/tageditor.dir/application/main.cpp.o
[ 28%] Building CXX object CMakeFiles/tageditor.dir/cli/attachmentinfo.cpp.o
[ 42%] Building CXX object CMakeFiles/tageditor.dir/cli/helper.cpp.o
[ 57%] Building CXX object CMakeFiles/tageditor.dir/cli/mainfeatures.cpp.o
/var/cache/glade/tageditor/application/main.cpp:25:17: error: ‘ConversionUtilities’ is not a namespace-name
 using namespace ConversionUtilities;
                 ^
/var/cache/glade/tageditor/application/main.cpp:25:36: error: expected namespace-name before ‘;’ token
 using namespace ConversionUtilities;
                                    ^
~~~

My build scripts:

http://github.com/svnpenn/glade

**Comment by Martchus** [comment]
Thanks for testing. I assume you rebuild c++utilities and tagparser before?

**Comment by svnpenn** [comment]
@Martchus completely clean build. Thank you for asking though, easy to forget

**Comment by Martchus** [comment]
@svnpenn The issue should be fixed with fe23039fc359692fdad98722e9411e006de99793.

**Comment by svnpenn** [comment]
@Martchus I did a Git Bisect. Here is the commit that is causing no output:

~~~
77da65ddf79bbcbe8b5f2f16d8125d4bf9e99d43 is the first bad commit
commit 77da65ddf79bbcbe8b5f2f16d8125d4bf9e99d43
Author: Martchus <martchus@gmx.net>
Date:   Sun Dec 18 17:23:45 2016 +0100

    Convert args to UTF-8 under Windows
~~~

https://github.com/Martchus/tageditor/commit/77da65ddf79bbcbe8b5f2f16d8125d4bf9e99d43

**Comment by svnpenn** [comment]
@Martchus it builds now, but still empty output. I did a Git Bisect. Here is the
commit that is causing no output:

~~~
77da65ddf79bbcbe8b5f2f16d8125d4bf9e99d43 is the first bad commit
commit 77da65ddf79bbcbe8b5f2f16d8125d4bf9e99d43
Author: Martchus <martchus@gmx.net>
Date:   Sun Dec 18 17:23:45 2016 +0100

    Convert args to UTF-8 under Windows
~~~

https://github.com/Martchus/tageditor/commit/77da65ddf79bbcbe8b5f2f16d8125d4bf9e99d43

**Comment by svnpenn** [comment]
@Martchus it builds now, but still empty output. I did a Git Bisect. Here is the
commit that is causing no output:

https://github.com/Martchus/tageditor/commit/77da65ddf79bbcbe8b5f2f16d8125d4bf9e99d43

~~~
77da65ddf79bbcbe8b5f2f16d8125d4bf9e99d43 is the first bad commit
commit 77da65ddf79bbcbe8b5f2f16d8125d4bf9e99d43
Author: Martchus <martchus@gmx.net>
Date:   Sun Dec 18 17:23:45 2016 +0100

    Convert args to UTF-8 under Windows
~~~

You might look at this:

https://github.com/stedolan/jq/issues/811

**Comment by svnpenn** [comment]
@Martchus it builds now, but still empty output. I did a Git Bisect. Here is the
commit that is causing no output:

https://github.com/Martchus/tageditor/commit/77da65ddf79bbcbe8b5f2f16d8125d4bf9e99d43

~~~
77da65ddf79bbcbe8b5f2f16d8125d4bf9e99d43 is the first bad commit
commit 77da65ddf79bbcbe8b5f2f16d8125d4bf9e99d43
Author: Martchus <martchus@gmx.net>
Date:   Sun Dec 18 17:23:45 2016 +0100

    Convert args to UTF-8 under Windows
~~~

You might look at this commit:

https://github.com/stedolan/jq/commit/7811ef1e1746f0963deb960af2c9623fb53c24a5

**Comment by Martchus** [comment]
Thanks for your help. The issue should be fixed in https://github.com/Martchus/cpp-utilities/commit/9a395a45d3a1ff64fff755be6bbb1aecf5bb9ff7. Issue #15 remains, of course. I also noticed that the terminal prompt isn't shown correctly when the application terminates. I guess this is due to the mentioned `::ApplicationUtilities::startConsole()` function. Maybe I can fix this, at least.

There was a stupid mistake in the conversion function introduced by that commit.
I wonder why it didn't cause any trouble when testing with Wine.

**Comment by svnpenn** [comment]
@Martchus confirmed fixed. Thanks
